### ISSUE TITLE
Failing to install on macOS 10.14.2

### ISSUE THREAD

**Issue by rossbulat** [bitcoinjs/tiny-secp256k1#32]
Node version: v8.12.0
yarn version: v1.12.3

Originally discovered when attempting ot install `js-ipfs`. Issue for that is open [here](https://github.com/ipfs/js-ipfs/issues/1769).

Failing to install. `npm i tiny-secp256k1` outputs:

```
module.js:550
    throw err;
    ^
Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

**Comment by junderw** [comment]
Could you try this?

https://stackoverflow.com/a/45348862/3074620

Or use node-brew instead to install node and npm, since brew is not too good:

https://github.com/hokaccha/nodebrew

**Comment by rossbulat** [comment]
@junderw The fresh reinstall of node worked. Thank you
```
sudo rm -rf /usr/local/lib/node_modules/npm
brew reinstall node
```
